### ISSUE TITLE
HTML Block with MJML

### ISSUE THREAD

**Issue by NorthstarTech** [ryandeba/grapesjs-html-block#1]
Great, Its work fine. If I want to create a html block with MJML framework, then How should I change this code? 

Thanks.

**Comment by ryandeba** [comment]
I am not very familiar with MJML, so I'm not sure how to best answer your question. There is an MJML plugin for grapes though: https://github.com/artf/grapesjs-mjml. Have you looked at that? Or perhaps you're already using it? 

From my understanding, MJML just provides an alternative way to write code for responsive emails. So when you click the "edit code" button, are you wanting to edit MJML code instead of HTML? Or toggle between the two?

If you could provide some more details about what your requirements are, I will try my best to assist further.

**Comment by NorthstarTech** [comment]
Yeah, Basically I am using the MJML framework with grapesjs for responsive emails. I want that, when I drag the html block, it creates the mjml tag for it ,instead of div tag. I think <mj-raw> displays the html in mjml, but I am not sure,either it will works or not. Is it possible for you to also update your html-block-js file according to mjml?

**Comment by ryandeba** [comment]
Could you just change the `content` value of the "html-code" block to some mjml tag instead of a div? Something like:
```
editor.BlockManager.add("html-code", {
      attributes: {class: "fa fa-code"},
      label: "MJML Code",
      content: '<mj-text data-html-code>Edit my MJML content</mj-text>'
});
```

Sorry, I'm not sure that I'm familiar enough with the relationship between MJML and HTML in the context of GrapesJS to be much help beyond that at this time.

**Comment by NorthstarTech** [comment]
Thank u so much @ryandeba  :+1:
